# Generated by Django 4.0.3 on 2022-03-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parent_child.parent')),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
    ]
